version: "3.7"
services:
  nubi-test:
    image: nubi-test:1.0.0
    build: ../application
    restart: always
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_USER=root
      - MONGO_PASSWORD=password
      - MONGO_DB=nubi-test-db
    ports:
      - 8080:8080
    volumes:
    ## DESCOMENTAR PARA DESARROLLO
      - ../application:/home/app
    user: root
    command: bash -c "python3.8 -m pip install -r requirements.txt && python3.8 -m pip install -e . && gunicorn --config /home/app/config/gunicorn.conf.py -b 0.0.0.0:8080 'nubi_test.app:start_server()'"
    networks:
      - test_net

  mongo:
    image: mongo:4.4.0
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./volumes/mongo:/data/db
      - /etc/localtime:/etc/localtime
    networks:
      - test_net

networks:
  test_net: